import type { Baufeld, BuildingModule, Manufacturer, BuildingShape } from "./types";

export const BAUFELDER: Baufeld[] = [];

export const MANUFACTURERS: Record<Manufacturer, { label: string; color: string; accent: string }> = {
  "gropyus": { label: "GROPYUS", color: "#3B82F6", accent: "#60A5FA" },
  "nokera": { label: "Nokera", color: "#06B6D4", accent: "#22D3EE" },
  "alho": { label: "ALHO", color: "#F59E0B", accent: "#FBBF24" },
  "goldbeck": { label: "Goldbeck", color: "#EF4444", accent: "#F87171" },
  "max-boegl": { label: "Max Bögl", color: "#8B5CF6", accent: "#A78BFA" },
};

export const SHAPE_CONFIG: Record<BuildingShape, { label: string; icon: string }> = {
  "riegel": { label: "Riegel", icon: "▬" },
  "l-winkel": { label: "L-Winkel", icon: "⌐" },
  "u-form": { label: "U-Form", icon: "⊔" },
  "punkthaus": { label: "Punkthaus", icon: "■" },
  "t-form": { label: "T-Form", icon: "⊤" },
  "doppelhaus": { label: "Doppelhaus", icon: "⊞" },
};

export const BUILDINGS: BuildingModule[] = [
  // ── GROPYUS (3) ──
  {
    id: "gropyus-riegel-36",
    name: "Riegel R-36",
    manufacturer: "gropyus",
    manufacturerLabel: "GROPYUS",
    shape: "riegel",
    shapeLabel: "Riegel",
    footprint: { width: 12, depth: 36 },
    minGeschosse: 3,
    maxGeschosse: 6,
    defaultGeschosse: 5,
    wePerGeschoss: 6,
    bgfPerGeschoss: 432,
    roofOptions: ["flat", "pult"],
    facadeOptions: ["putz", "klinker", "holz"],
    energyRating: "A+",
    pricePerSqm: 1890,
    tags: ["holzbau", "kfw40", "barrierefrei"],
    color: "#3B82F6",
    rendering: "/uplan-engine/renderings/optimized/gropyus-riegel-36.jpg",
  },
  {
    id: "gropyus-punkt-16",
    name: "Punkt P-16",
    manufacturer: "gropyus",
    manufacturerLabel: "GROPYUS",
    shape: "punkthaus",
    shapeLabel: "Punkthaus",
    footprint: { width: 16, depth: 16 },
    minGeschosse: 4,
    maxGeschosse: 8,
    defaultGeschosse: 6,
    wePerGeschoss: 2,
    bgfPerGeschoss: 256,
    roofOptions: ["flat"],
    facadeOptions: ["putz", "metall"],
    energyRating: "A+",
    pricePerSqm: 2150,
    tags: ["kfw40", "barrierefrei", "aufzug"],
    color: "#3B82F6",
    rendering: "/uplan-engine/renderings/optimized/gropyus-punkt-16.jpg",
  },
  {
    id: "gropyus-u-36",
    name: "U-Block U-36",
    manufacturer: "gropyus",
    manufacturerLabel: "GROPYUS",
    shape: "u-form",
    shapeLabel: "U-Form",
    footprint: { width: 36, depth: 24 },
    minGeschosse: 4,
    maxGeschosse: 6,
    defaultGeschosse: 5,
    wePerGeschoss: 8,
    bgfPerGeschoss: 648,
    roofOptions: ["flat", "pult"],
    facadeOptions: ["putz", "klinker"],
    energyRating: "A",
    pricePerSqm: 1780,
    tags: ["kfw40", "innenhof"],
    color: "#3B82F6",
    rendering: "/uplan-engine/renderings/optimized/gropyus-u-36.jpg",
  },
  // ── Nokera (2) ──
  {
    id: "nokera-riegel-30",
    name: "Riegel R-30",
    manufacturer: "nokera",
    manufacturerLabel: "Nokera",
    shape: "riegel",
    shapeLabel: "Riegel",
    footprint: { width: 12, depth: 30 },
    minGeschosse: 3,
    maxGeschosse: 5,
    defaultGeschosse: 4,
    wePerGeschoss: 5,
    bgfPerGeschoss: 360,
    roofOptions: ["flat", "saddle"],
    facadeOptions: ["holz", "putz"],
    energyRating: "A+",
    pricePerSqm: 2050,
    tags: ["holzbau", "kfw40", "passivhaus"],
    color: "#06B6D4",
    rendering: "/uplan-engine/renderings/optimized/nokera-riegel-30.jpg",
  },
  {
    id: "nokera-l-24",
    name: "L-Winkel L-24",
    manufacturer: "nokera",
    manufacturerLabel: "Nokera",
    shape: "l-winkel",
    shapeLabel: "L-Winkel",
    footprint: { width: 24, depth: 24 },
    minGeschosse: 3,
    maxGeschosse: 5,
    defaultGeschosse: 4,
    wePerGeschoss: 4,
    bgfPerGeschoss: 384,
    roofOptions: ["flat", "pult"],
    facadeOptions: ["holz", "putz", "klinker"],
    energyRating: "A+",
    pricePerSqm: 2200,
    tags: ["holzbau", "passivhaus", "barrierefrei"],
    color: "#06B6D4",
    rendering: "/uplan-engine/renderings/optimized/nokera-l-24.jpg",
  },
  // ── ALHO (2) ──
  {
    id: "alho-riegel-42",
    name: "Riegel R-42",
    manufacturer: "alho",
    manufacturerLabel: "ALHO",
    shape: "riegel",
    shapeLabel: "Riegel",
    footprint: { width: 14, depth: 42 },
    minGeschosse: 3,
    maxGeschosse: 6,
    defaultGeschosse: 4,
    wePerGeschoss: 7,
    bgfPerGeschoss: 588,
    roofOptions: ["flat"],
    facadeOptions: ["metall", "putz"],
    energyRating: "A",
    pricePerSqm: 1650,
    tags: ["modulbau", "stahl", "schnellbau"],
    color: "#F59E0B",
    rendering: "/uplan-engine/renderings/optimized/alho-riegel-42.jpg",
  },
  {
    id: "alho-t-32",
    name: "T-Block T-32",
    manufacturer: "alho",
    manufacturerLabel: "ALHO",
    shape: "t-form",
    shapeLabel: "T-Form",
    footprint: { width: 24, depth: 32 },
    minGeschosse: 4,
    maxGeschosse: 6,
    defaultGeschosse: 5,
    wePerGeschoss: 6,
    bgfPerGeschoss: 528,
    roofOptions: ["flat", "pult"],
    facadeOptions: ["metall", "putz", "klinker"],
    energyRating: "B",
    pricePerSqm: 1580,
    tags: ["modulbau", "stahl"],
    color: "#F59E0B",
    rendering: "/uplan-engine/renderings/optimized/alho-t-32.jpg",
  },
  // ── Goldbeck (3) ──
  {
    id: "goldbeck-punkt-18",
    name: "Punkt P-18",
    manufacturer: "goldbeck",
    manufacturerLabel: "Goldbeck",
    shape: "punkthaus",
    shapeLabel: "Punkthaus",
    footprint: { width: 18, depth: 18 },
    minGeschosse: 3,
    maxGeschosse: 8,
    defaultGeschosse: 5,
    wePerGeschoss: 3,
    bgfPerGeschoss: 324,
    roofOptions: ["flat"],
    facadeOptions: ["putz", "klinker", "metall"],
    energyRating: "A",
    pricePerSqm: 1720,
    tags: ["systembau", "kfw40"],
    color: "#EF4444",
    rendering: "/uplan-engine/renderings/optimized/goldbeck-punkt-18.jpg",
  },
  {
    id: "goldbeck-doppel-12",
    name: "Doppel D-12",
    manufacturer: "goldbeck",
    manufacturerLabel: "Goldbeck",
    shape: "doppelhaus",
    shapeLabel: "Doppelhaus",
    footprint: { width: 12, depth: 12 },
    minGeschosse: 2,
    maxGeschosse: 3,
    defaultGeschosse: 2,
    wePerGeschoss: 2,
    bgfPerGeschoss: 144,
    roofOptions: ["flat", "saddle", "pult"],
    facadeOptions: ["putz", "klinker", "holz"],
    energyRating: "A",
    pricePerSqm: 1950,
    tags: ["eigentum", "reihenbau"],
    color: "#EF4444",
    rendering: "/uplan-engine/renderings/optimized/goldbeck-doppel-12.jpg",
  },
  {
    id: "goldbeck-u-30",
    name: "U-Block U-30",
    manufacturer: "goldbeck",
    manufacturerLabel: "Goldbeck",
    shape: "u-form",
    shapeLabel: "U-Form",
    footprint: { width: 30, depth: 20 },
    minGeschosse: 4,
    maxGeschosse: 6,
    defaultGeschosse: 5,
    wePerGeschoss: 6,
    bgfPerGeschoss: 480,
    roofOptions: ["flat"],
    facadeOptions: ["klinker", "putz", "metall"],
    energyRating: "B",
    pricePerSqm: 1620,
    tags: ["systembau", "innenhof"],
    color: "#EF4444",
    rendering: "/uplan-engine/renderings/optimized/goldbeck-u-30.jpg",
  },
  // ── Max Bögl (2) ──
  {
    id: "maxboegl-riegel-48",
    name: "Riegel R-48",
    manufacturer: "max-boegl",
    manufacturerLabel: "Max Bögl",
    shape: "riegel",
    shapeLabel: "Riegel",
    footprint: { width: 14, depth: 48 },
    minGeschosse: 4,
    maxGeschosse: 7,
    defaultGeschosse: 5,
    wePerGeschoss: 8,
    bgfPerGeschoss: 672,
    roofOptions: ["flat"],
    facadeOptions: ["putz", "klinker", "metall"],
    energyRating: "A",
    pricePerSqm: 1550,
    tags: ["betonfertigteil", "großserie"],
    color: "#8B5CF6",
    rendering: "/uplan-engine/renderings/optimized/maxboegl-riegel-48.jpg",
  },
  {
    id: "maxboegl-l-28",
    name: "L-Winkel L-28",
    manufacturer: "max-boegl",
    manufacturerLabel: "Max Bögl",
    shape: "l-winkel",
    shapeLabel: "L-Winkel",
    footprint: { width: 28, depth: 28 },
    minGeschosse: 4,
    maxGeschosse: 6,
    defaultGeschosse: 5,
    wePerGeschoss: 5,
    bgfPerGeschoss: 520,
    roofOptions: ["flat", "pult"],
    facadeOptions: ["putz", "klinker"],
    energyRating: "A",
    pricePerSqm: 1680,
    tags: ["betonfertigteil", "kfw40"],
    color: "#8B5CF6",
    rendering: "/uplan-engine/renderings/optimized/maxboegl-l-28.jpg",
  },
  // ── Nokera (3) ──
  {
    id: "nokera-riegel-40",
    name: "Riegel R-40",
    manufacturer: "nokera",
    manufacturerLabel: "Nokera",
    shape: "riegel",
    shapeLabel: "Riegel",
    footprint: { width: 13, depth: 40 },
    minGeschosse: 3,
    maxGeschosse: 7,
    defaultGeschosse: 5,
    wePerGeschoss: 6,
    bgfPerGeschoss: 520,
    roofOptions: ["flat", "pult"],
    facadeOptions: ["holz", "putz"],
    energyRating: "A+",
    pricePerSqm: 1850,
    tags: ["holzmodulbau", "kfw40", "seriell", "barrierefrei"],
    color: "#06B6D4",
    rendering: "/uplan-engine/renderings/optimized/nokera-riegel-40.jpg",
  },
  {
    id: "nokera-punkt-15",
    name: "Punkt P-15",
    manufacturer: "nokera",
    manufacturerLabel: "Nokera",
    shape: "punkthaus",
    shapeLabel: "Punkthaus",
    footprint: { width: 15, depth: 15 },
    minGeschosse: 3,
    maxGeschosse: 6,
    defaultGeschosse: 5,
    wePerGeschoss: 3,
    bgfPerGeschoss: 225,
    roofOptions: ["flat"],
    facadeOptions: ["holz", "putz", "metall"],
    energyRating: "A+",
    pricePerSqm: 2050,
    tags: ["holzmodulbau", "kfw40", "nachverdichtung", "aufzug"],
    color: "#06B6D4",
    rendering: "/uplan-engine/renderings/optimized/nokera-punkt-15.jpg",
  },
  {
    id: "nokera-riegel-54",
    name: "Riegel R-54",
    manufacturer: "nokera",
    manufacturerLabel: "Nokera",
    shape: "riegel",
    shapeLabel: "Riegel",
    footprint: { width: 14, depth: 54 },
    minGeschosse: 4,
    maxGeschosse: 7,
    defaultGeschosse: 6,
    wePerGeschoss: 9,
    bgfPerGeschoss: 756,
    roofOptions: ["flat"],
    facadeOptions: ["holz", "putz", "klinker"],
    energyRating: "A+",
    pricePerSqm: 1720,
    tags: ["holzmodulbau", "kfw40", "seriell", "großserie"],
    color: "#06B6D4",
    rendering: "/uplan-engine/renderings/optimized/nokera-riegel-54.jpg",
  },
];
